// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqdotpfvivoqajlaoljp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxZG90cGZ2aXZvcWFqbGFvbGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDI1NDIsImV4cCI6MjA3MTAxODU0Mn0.Rkg2zLkWT0acei1l9VOjwf3G74oHB5w834ke0ysnlFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});